### ISSUE TITLE
Add prestart() and poststop() method in ControlScript

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#105]
Some operations needs to be done before the process is started or when the process is supposed to be stopped. The call in loop of the prestart and poststop methods should be added in the ControlScript. Empty method prestart and poststop should be added to the class ControlAction and may be overriden by subclasses. 

class ControlScript(object):
	""" Control script """
	
	def start(self):
		...
+		for controlAction in self.controlActions:
+			if controlAction.active:
+				controlAction.prestart()
		for controlAction in self.controlActions:
			if controlAction.active:
				controlAction.start()
	
	def stop(self):
		""" Method called on stop, stops control actions in reverse order """
		for controlAction in self.controlActions[::-1]:
			controlAction.stop()
+		for controlAction in self.controlActions[::-1]:
+			controlAction.poststop()

class ControlAction(object):
	""" Control script action """
	...
+	def prestart(self):
+		""" Method called on start, to be overridden by subclasses """
+		pass
	def start(self):
		""" Method called on start, to be overridden by subclasses """
		pass

	def stop(self):
		""" Method called on stop, to be overridden by subclasses """
		pass
+	def poststop(self):
+		""" Method called on stop, to be overridden by subclasses """
+		pass

**Comment by dergo** [comment]
Proposed solution seems to be the good solution for me, so I close the issue.
