### ISSUE TITLE
Inconsistent character set used in generated test script doc

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#112]
The generated test script documentation is defined as being encoded in UTF-8 while some parts are generated in ISO-LATIN-1 encoding.

The encoding is defined as UTF-8:
&lt;META http-equiv="Content-Type" content="text/html; charset=UTF-8"&gt;

Some parts are generated in ISO-LATIN-1 encoding:
In file tools/TestProcedureDoc/generateTestCampaignDoc.py, line 201:
    testStepsTable = et.tostring(testStepsTableHtmlTree, 'iso-8859-1')

**Comment by dergo** [comment]
Generated test campaign doc still contains characters encoded in ISO-8859-1 (non-breakable space I think) instead of UTF-8, resulting in <?> being displayed in the result column.

**Comment by simjan** [comment]
after the html conversion, the script replaces all "non breakable spaces" by "&nbsp;"
This fix the problem with this character....

**Comment by dergo** [comment]
I think non-breakable spaces were expressly used, but I don't remember why (maybe for HTML import in Word ?).
If we don't need them then use spaces directly instead of using them and converting them afterwards.

**Comment by simjan** [comment]
I don't know the reason why we use non breakable spaces....
LVB?

**Comment by lvboque** [comment]
let's try with simple space ...

IMO, there is no specific reason!

**Comment by dergo** [comment]
But if user wants to put non-breakable spaces in the doc for any reason,
they should remain non-breakable spaces!

**Comment by simjan** [comment]
if a step has &nbsp; in its documentation, it's kept as a non breakable space in the generated campaign documentation.

**Comment by dergo** [comment]
I just tried to put `&nbsp;` in test script doc, it results in `<?>` being displayed in the generated documentation.

**Comment by simjan** [comment]
The nbsp character cannot be managed by the XSLT system... if I use the character itself or ```&#160;``` or ```&nbsp;``` I've got an error in the xml parsing...
```java
Line #6; Column #128; XSLT Error (javax.xml.transform.TransformerException): javax.xml.transform.TransformerException: org.apache.xml.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
Exception in thread "main" java.lang.RuntimeException: javax.xml.transform.TransformerException: org.apache.xml.utils.WrappedRuntimeException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.apache.xalan.xslt.Process.doExit(Process.java:1155)
	at org.apache.xalan.xslt.Process.main(Process.java:1128)
	at com.qspin.qtaste.util.GenerateTestScriptDoc.generate(GenerateTestScriptDoc.java:80)
	at com.qspin.qtaste.util.GenerateTestScriptDoc.main(GenerateTestScriptDoc.java:95)

```

**Comment by dergo** [comment]
The problem is that XSLT interprets the file as being encoded in UTF-8
while it seems to be in ISO-8859-1.
We shouldn't use ISO-8859-1 in any files, including intermediary ones, they
should be encoded in UTF-8.

Note that the problem is, I think, not limited to non-breakable space, it
probably occurs for any non-ASCII character.

2015-11-16 15:28 GMT+01:00 simjan <notifications@github.com>:

**Comment by simjan** [comment]
It seems that the ElementTree class write some character in the file without specifying the encoding...
If I force the encoding usage everywhere, the file encoding is utf-8...

**Comment by simjan** [comment]
If a python script is imported with "import...." no problem with special character (&nbsp;)
If a python script is imported with "importTestScript...." no problem with special character (&nbsp;)
BUT if the special character is used in the main script, I still have problem with the encoding... Probably linked with the way the file is read.... keep investigating....

**Comment by simjan** [comment]
waiting for validation...

**Comment by lvboque** [comment]
1/ Still some problems ....

If you add a step with the following comments in the testscript
" Degree: °, éàè, &eacute; &amp; ok ?" ...
I got: 
"Degree: Â°, Ã©Ã Ã¨, é & ok ?" in the QTaste documentation tab!

Not the expected documentation!

2/ There is still a lot of debug output like:
"Generating documentation of test documentation included in pythonlib directories.
1 directory(ies) found
1 script(s) found
"
3/ Do you still need this code?
content = content.replace(' ', '&#160;').replace('&#160;','&nbsp;')

4/ dump method should be removed

5/ Is it possible to improve the code to define an encoding while generating the qtaste documentation instead of forcing the encoding to UTF-8 (which introduce a change in the jython library and so potentially introduce side effects....)

  file.write("<?xml version='1.0' encoding='%s'?>\n" % encoding.encode(encoding))

**Comment by simjan** [comment]
the encoding is forced ONLY if it's not defined...
The java code calling the pythonlib.py script can be updated in order to provide the encoding... I don't know if the documentation generation system can support all encodings... And the jython lib is bugged by default so...

**Comment by lvboque** [comment]
I still see a problem ... if you create a step description like this one
"@step      Ã‚Â°, ÃƒÂ©ÃƒÂ ÃƒÂ¨, éDescription of the actions&nbsp;done for this step"
I got "ÃƒâšÃ‚Â°, ÃƒÆ’Ã‚Â©ÃƒÆ’Ã‚ ÃƒÆ’Ã‚Â¨, Ã©Description of the actions done for this step" displayed in the Documentation tab ....

(was working fine in V2.2.2)

**Comment by simjan** [comment]
can you check with these modifications?
