### ISSUE TITLE
"Copy/Rename test script" enhancements

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#126]
When using "Copy test script" or "Rename test script" the default value is currently empty.

1) It would be better to use the name of the copied/renamed test script as default value, as the target name will probably be close to the initial name.

2) The OK button should be disabled if the given name is the same as the initial name.

**Comment by remybaranx** [comment]
I think this issue is fixed.

For the point (2), it also disables the 'OK' button if the new name is empty.

**Comment by lvboque** [comment]
Could you check if it was fixed in 2.3.0 and simply regenerate the release notes?
Thks

**Comment by simjan** [comment]
included in 2.3.0
