### ISSUE TITLE
GUI testscript editor should convert tabs into 4 spaces

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#131]
In Python, you can use spaces or tabs for blocks indentation, however, you cannot mix tabs and spaces in the same block (and in Python 3 you cannot mix them at all).

As in Python, spaces are the preferred indentation method, QTaste should convert tabs into 4 spaces when saving test scripts.
In addition, tab could also be automatically converted to 4 spaces while typing.

**Comment by remybaranx** [comment]
So, tabs must be replaced by spaces when : 
- a file is loaded (at startup or when this file is edited outside QTaste).
- the source code is edited inside QTaste (on the fly, copy/paste from an external editor, ...).
- the source code is saved in QTaste.

**Comment by remybaranx** [comment]
Correction commited on the master branch.

- If the test script is automatically modified while loading (at startup or when the test script has been edited outside QTaste), a popup informs the user about this modification.
- tabulations are also automatically replaced while typing.

**Comment by lvboque** [comment]
Could you check if it was fixed in 2.3.0 and simply regenerate the release notes?
Thks

**Comment by simjan** [comment]
included in 2.3.0
