### ISSUE TITLE
JUnit/TeamCity tests results integration

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#157]
A special JUnit reporter should be added to allow dynamic tests results feedback in TeamCity.
(or the existing XML reporter could be adapted/made configurable so that it works for that purpose).

An XML file has to be written for each test, instead of a global one with all tests results, because TeamCity treats the XML files as soon as it detects them and doesn't treat them further if they are updated.

Some draft code has been sent by Christophe Broeckx to dergo and lvboque.

**Comment by qspin** [comment]
To dergo for status of the issue

**Comment by pguermo** [comment]
To dergo for code review

**Comment by dergo** [comment]
See comments on code.
I will correct issues and commit.

**Comment by dergo** [comment]
To pguermo to retest after code cleanup.

**Comment by lvboque** [comment]
Validated by pguermo!

Closed!
