### ISSUE TITLE
Add jacoco parameters in control scripts

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#161]
It should be possible to pass jacoco parameters to the jacoco agent when using useJacoco=True in a control script action, at least to set the inclusions and exclusions.

Instead of just passing the following argument to the jvm:
-javaagent:...jacocoagent.jar=append=true,destfile=reports/file.jacoco
It would be useful to be able to pass e.g.
-javaagent:...jacocoagent.jar=append=true,destfile=reports/file.jacoco,includes=...,excludes=...

We could either add jacocoIncludes and jacocoExcludes parameters, or a single jacocoParameters parameter that we would have to build ourselves but that would allow to set also other parameters (yet I don't think others are so useful).

Jacoco agent parameters are defined here: http://www.eclemma.org/jacoco/trunk/doc/agent.html.

**Comment by remybaranx** [comment]
This new feature has been added into the control script file of the branch control_script_2.7 (so, it requires jython 2.7.0).

Do you also need this feature in the current control script or is it ok for you to wait for the end of the jython 2.7.0 integration ?

**Comment by simjan** [comment]
I integrated the jacoco parameter code in the master branch...
SUT are started/stopped but I cannot check jacoco output...

**Comment by lvboque** [comment]
Could you check as example that the jacoco file is updated and become
bigger if you test more code
(ex: execute a test on buttons on the SUT javagui demo, check the jacoco
file size ... then execute test for a table on the SUT javagui demo, check
that the jacoco file is bigger and updated)?

Thks

**Comment by simjan** [comment]
For a same test, file size are differents when includes/excludes parameters are changed.

Validated
