### ISSUE TITLE
Infinite loop in javagui

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#165]
Hello,

It seems there is an infinite loop in the code plugins_src/javagui/src/main/java/com/qspin/qtaste/javagui/server/TextSetter.java:

        private void forceToLooseFocus(Component c) {
                Container parent= c.getParent();
                while ( parent != null && !parent.isFocusable() )
                {
                       parent.getParent(); // < ==== HERE
                }
                if ( parent != null ) {
                        parent.requestFocus();
                }
        }

I think it should be parent = parent.getParent();

Best regards,
Patrick

**Comment by dergo** [comment]
Fix committed, tested successfully.
