### ISSUE TITLE
Test suite execution: Log level configuration is not kept after switching from Result tab to Logs tab

### ISSUE THREAD

**Issue by remybaranx** [qspin/qtaste#170]
In the Result tab, I check Trace and Debug levels, but when I switch to the Logs tab, Trace and Debug are not checked and not taken into account.

**Comment by dergo** [comment]
Not sure this should be considered as a bug, the log panels in Result and Logs are really separated...

**Comment by remybaranx** [comment]
Yes, I agree, it depends on how we use QTaste.

I often switch to the Log tab, because my screen is quite small (laptop 15') and it's hard to read logs on the Result tab. Most of the time, I begin by checking Trace/Debug levels on the Result tab, then I see that it's hard to read logs and I switch to the Logs tab.

**Comment by lvboque** [comment]
OK to close
