### ISSUE TITLE
JavaGUI getSelectedValue() doesn't work on AbstractButton (like JCheckBox)

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#171]
JavaGUI getSelectedValue() doesn't work on AbstractButton, like a JCheckBox, it throws an exception saying the component is not supported.

Also part of the javadoc is a copy-paste of the doc of selectValue() (references to setters instead of getters).

**Comment by dergo** [comment]
Note: getting the value is done in ValueGetter.executeCommand().

**Comment by remybaranx** [comment]
I think the bug is fixed. (See https://github.com/qspin/qtaste/pull/172)

**Comment by remybaranx** [comment]
Sorry to always rename the variable 'c' to 'component' but I hate variable names which mean nothing ;-)

**Comment by remybaranx** [comment]
To validate (See https://github.com/qspin/qtaste/pull/172)

**Comment by remybaranx** [comment]
The pull request #172 has been reviewed and merged, so I close this ticket.
