### ISSUE TITLE
Cannot get Boolean attribute from a MI

### ISSUE THREAD

**Issue by simjan** [qspin/qtaste#177]
MultipleInstancesFactory cannot invoke the constructor of com.qspin.qtaste.testapi.impl.demo.VaadinImpl
java.util.NoSuchElementException: 'multiple_instances_components.Vaadin (0).hasToClose' doesn't map to an existing object

there is an additional space before de (0)

**Comment by simjan** [comment]
to follow the process...

fo validation

**Comment by dergo** [comment]
Validated ok by review.
