### ISSUE TITLE
Subtitler test api implementation should access GUI in Swing thread

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#178]
The Subtitler test api implementation should call the GUI methods in the Swing thread.

**Comment by remybaranx** [comment]
I fixed this issue -> to validate.

**Comment by dergo** [comment]
Issues:
- call to ```initialize()``` has been removed from constructor, so it's not called for the first test
- ```System.out.println()``` calls have been added
- e.printStackTrace() should not be used, but replaced by logs
- not related to change, bug ```m_abort``` variable should be declared volatile and you should wait for the thread termination in terminate() to avoid issues if initialize() is called too fast after terminate() + use clean code to avoid sleep 1 second when aborting
- or actually better to replace custom thread, sleep, m_abort variable and invokeAndWait, by a simple javax.swing.Timer, it will be a lot simpler

**Comment by remybaranx** [comment]
modifications done.
I have replaced the thread by a swing timer.

**Comment by dergo** [comment]
Test not successful.

In test mode, e.g. executing "Selection" test, it seems it doesn't show the first subtitle "Select 3rth element in a List".

When you commit, please use "issue #178" instead of "bug#178", otherwise it's not detected as a reference to this issue and doesn't appear in the issue page.

**Comment by remybaranx** [comment]
No problem for the "selection" test on my PC (Ubuntu 14.04, qtaste master).
I see : 
"Select the tab by id"
"Select 3rth element in a List"
...

Ok for the commit message, i didn't know (bug#178 was an old habit).

**Comment by lvboque** [comment]
Could you check if it was fixed in 2.3.0 and simply regenerate the release notes?
Thks

**Comment by simjan** [comment]
included in 2.3.0
