### ISSUE TITLE
getSelectedValue should return Object, getSelectedText should return String, getSelectedIndex should return a int

### ISSUE THREAD

**Issue by lvboque** [qspin/qtaste#184]
getSelectedValue shoud return an Object, depending on the kind of GUI component more methods will be accessible to TestScripts. I.e: If the component is a checkbox, the returned value will be boolean.

getSelectedIndex should return the index of the selected item: can be useful if you don't care about the text but about the position in a list.

getSelectedText should return the text of the selected value

**Comment by simjan** [comment]
all tests are green and code seems ok

**Comment by dergo** [comment]
Note that there is no getSelectedText() method, but I don't think it's necessary, as one can use getSelectedValue() instead.

**Comment by simjan** [comment]
It depends....
From a combobox, if the test has to retrieve the model object or the text representation inside the combobox...
