### ISSUE TITLE
TestCampaign documentation generation doesn't work anymore

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#187]
TestCampaign documentation generation doesn't work anymore in QTaste v2.2.2 (nor latest master version), while it was working in v2.2.1.

In demo directory:
 - ~/qtaste-2.2.1/bin/generate-TestCampaign-doc.sh TestCampaigns/AllLinuxDemo.xml
   ...
   Generated TestCampaigns/AllLinuxDemo-doc.html successfully.

 - ~/qtaste-2.2.2/bin/generate-TestCampaign-doc.sh TestCampaigns/AllLinuxDemo.xml
   ...
   Creating Test suite frameset in TestSuites/Process/TestSuite-doc.html
   Exception occurs executing PythonInterpreter:no public constructors for com.qspin.qtaste.testsuite.impl.MetaTestSuite

**Comment by remybaranx** [comment]
The MetaTestSuite constructor visibility was changed from public to private and was "replaced" by a createTestSuite method, in another issue.

The generateTestCampaignDoc.py script has been updated according to this modification.

**Comment by dergo** [comment]
Fix validated.
