### ISSUE TITLE
For reporting purpose, it's required to know the line number currently used in testdata.csv

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#189]
The method testData.getRowId() should be accessible in the testscript to be able to know the line in the testdata.csv file actually used for the test.

PATCH:
```
--- JythonTestScript.java       (revision 72311)
+++ JythonTestScript.java       (working copy)
@@ -1307,6 +1307,10 @@
         public boolean contains(String name) {
             return testData.contains(name);
         }
+
+       public int getRowId() {
+           return testData.getRowId();
+       }
     }

     /**

**Comment by simjan** [comment]
Where will you use this "feature"?
The report already contains test data information... Why do you want this?

**Comment by pguermo** [comment]
As the data present in the report are really limited and it's not possible to inject generated data/string/links to images during the test, we have to generate a side report.

**Comment by dergo** [comment]
Note that an (ugly) workaround is possible, you can access it by launching QTaste with security access disabled (```-Dpython.security.respectJavaAccessibility=false```)
then call ```getattr(testData,"this$0").testData.getRowId()```.

**Comment by pguermo** [comment]
To avoid to have to patch the coming version, please add this 3 lines on the trunk. Thanks !
