### ISSUE TITLE
In campaign report, an other status should be visible for testsuite passed with retry

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#192]
The return code of qtaste is different of zero (1) after having launched a test campaign but when I give a look to the report, I see all the testsuites are passed with the green V sign. Going inside the report of the testsuites, I see some of them have required a restart.

In such a case, in the campaign report, the V sign of the relative testsuite should have a different color (orange ?) or a different sign.

**Comment by pguermo** [comment]
A green flag in the test campaign report is understood as "testsuite OK" by the testers. They don't investigate further as the instability is not visible.

This green flag is a false positive !

**Comment by lvboque** [comment]
Is this modification acceptable for the campaigns of your team?

**Comment by dergo** [comment]
New behavior is acceptable and validated.
