### ISSUE TITLE
can you please explain the code ,which you have done as a demo for opc ua and output of it looks like

### ISSUE THREAD

**Issue by manikandankasi** [qspin/qtaste#193]

**Comment by simjan** [comment]
Which part of the code? About the test, the testAPI, the probe?

**Comment by manikandankasi** [comment]
i have seen your code and i have tried demo opc with client and server,but i have a doubt about opc ua and if its possible tell me your personal mail ,i can mail you clearly and am waiting for your reply

**Comment by dergo** [comment]
Closed because this is not an issue, you can contact us at info@qspin.be if needed.
