### ISSUE TITLE
QTaste release procedure doesn't work well with java 1.8

### ISSUE THREAD

**Issue by qspin** [qspin/qtaste#194]
Please fix all the javadoc inconsistencies (especially in javagui) that prevent the release script to release using java 1.8

To reproduce the issue, just start the releaseAll.sh script using a java 1.8 jvm

http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by dergo** [comment]
I fixed the javadoc errors (mvn javadoc:aggregate is now successful) and some of the warnings.

There are still javadoc warnings but they shouldn't prevent the release.

Couldn't test using releaseAll.sh, don't know how to run it without having the error "Cannot obtain passphrase in batch mode".
