### ISSUE TITLE
Installer izpack-5.0.0-beta10 cannot be used in console mode

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#196]
Izpack-5.0.0-beta10 is not able due to bug to generate the automatic installation script. Moreover a valid installation script cannot be used to install QTaste in console.

The two following modifications are required:

izpack/pom.xml
```
     <plugins>
       <plugin>
         <groupId>org.codehaus.izpack</groupId>
         <artifactId>izpack-maven-plugin</artifactId>
         <version>5.0.0-beta10</version>
```

=>
```
          <version>5.0.0-rc2</version>
```         

izpack/install.xml
```
<installation version="1.0">
```
=>
```
 <installation version="5.0">
```

Validation on OpenSuse:
Build all: OK
Manual installation in GUI mode: OK
Generation of the automatic script: OK
Installation with the automatic installation script: OK
TestCampaign QTASTE_V_and_V: OK

**Comment by simjan** [comment]
I just test the installer and it's working on Ubuntu... (I launched it from a terminal...)
Do you modify something?

**Comment by pguermo** [comment]
I haven't modified anything on GIT. 
The first problem is the generation of the automatic installation script. The one generated is empty.

Secondly, if you have a valid install script (generated with izpack 5.0.0-rc2) it doesn't work with the current version of QTaste using the version 5.0.0-beta10.

**Comment by simjan** [comment]
an error and a warning are still in the izpack output  (when used from command line) but without impact on the installation

**Comment by dergo** [comment]
We should use latest release (5.0.6) of izpack, not an old RC version.
If it doesn't work transparently with it, please update what is needed to make it work.

**Comment by simjan** [comment]
the last version of izpack is now used.

**Comment by dergo** [comment]
Validated on version c5bfdb8b.
