### ISSUE TITLE
V&V test QTASTE_SCRIPT_07 not implemented

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#199]
The V&V test TestSuites/TestSuite_QTaste/EngineSuite/QTASTE_SCRIPT/QTASTE_SCRIPT_07/TestScript.py is not implemented.

**Comment by dergo** [comment]
Actually the test was well implemented: step1() checking that variable doesn't exist, defining the variable after step1(), and useless steps 2 and 3, but I agree it was not clean, so I committed a cleaner implementation of the test.
