### ISSUE TITLE
Sikuli: library dependencies / test on different operating systems

### ISSUE THREAD

**Issue by jsorriaux** [qspin/qtaste#208]
Hello,

I faced an issue about library dependencies while trying to run sikuli API. opencv-dev and tessarect3 packages were missing. After installing them, it works well.

log : [Sikuli.txt](https://github.com/qspin/qtaste/files/399594/Sikuli.txt)

Operating system tested:
- Windows 7 -> ok
- Ubuntu 14.04 LTS-> ok 
- Opensuse 11.4 ->not ok, dependencies missing and could not resolve them unless to update the kernel (libc library was in the missing dependencies).
- Opensuse 12.3 -> ok

Jefferson

**Comment by qspin** [comment]
Thanks Jefferson for the feedback! Proposal is to close that issue! This is related to Sikulix pre-requirements
