### ISSUE TITLE
Sikuli enhancements

### ISSUE THREAD

**Issue by simjan** [qspin/qtaste#209]
features not implemented:
- find
- findAll
- onAppear
- onVanish
- onChange
- observe

verb change :
- exist should be renamed as exists
- exist should return false in stade of throwing an exception

problem:
- hover seems not working

**Comment by simjan** [comment]
find and findAll can't be implemented cause the region object (returned by these methods) cannot be serialized and so returned through the JMX system...

on*****Methods can be implemented as a kind of wait method.... When calling a on method, the script will continue after the "event"....
The problem is the java code cannot call back the Jython code in order to execute some specific code...

**Comment by dergo** [comment]
Maybe find and findAll could return a Rectangle which is serializable (you can convert Region to/from Rectangle) in the server part.

**Comment by simjan** [comment]
if the final user want to do something like 
```python
for area in sikuli.findAll(OK_BUTTON):
    area.click()
```
this solution will not be accepted... but if it's acceptable to have code like bellow:
```python
for area in sikuli.findAll(OK_BUTTON):
    sikuli.click(area)
```

**Comment by dergo** [comment]
Indeed, or you can return a serializable Wrapper of Rectangle, on which you implement click() and other needed methods...
then area.click() will be possible

**Comment by lvboque** [comment]
Thanks Simon, but I still have some scenario not manage properly ...
Let's suppose you have an interface like this one .... (look at find-click.png)
![find-click](https://cloud.githubusercontent.com/assets/448306/18304755/7c03e9be-74e4-11e6-9e8b-6b5f9e07a644.png)

It is possible to select an item using the "find" method ....
And then you get an "Area" Object .... 
![archiving_load_openfiles_opendicomdir_pnl](https://cloud.githubusercontent.com/assets/448306/18304899/43bb4632-74e5-11e6-8e40-926a9da347ae.png)


In the current implementation, this is not possible to click on the "..." which is the clickable region ...
![archiving_load_openfiles_opendicomdir_btn](https://cloud.githubusercontent.com/assets/448306/18304842/00087108-74e5-11e6-90f9-938b8e8a7d50.png)

Well, basically, we should be able to call click method with additional image parameter

**Comment by simjan** [comment]
It's possible, 
cfr : https://github.com/qspin/qtaste/blob/master/demo/TestSuites/Sikuli/Sikuli_playback_03/TestScript.py#L43

**Comment by lvboque** [comment]
Well, I don't see any method like click("xxx") 
The only one is click() without parameters

/** 
27 	 * Simulates a click on the center of the area. 
28 	 */ 
29 	public void click() 
30 	{ 
31 		new Region(this.rect).click(); 
32 	} 
33

**Comment by qspin** [comment]
I propose to close this issue! New enhancement will be proposed using other tickets

**Comment by lvboque** [comment]
Development validated with 3.0.0!
