### ISSUE TITLE
None should be returned when the conversion of a testdata cell fails

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#214]
By now, a test error is returned when the conversion (testdata.getIntValue()) of a cell of the testdata occurs (e.g. empty cell). As the content of a cell could be used only for some tests, an empty cell should be allowed. In such a case the conversion should return None,

**Comment by dergo** [comment]
As documented in com.qspin.qtaste.testsuite.TestData, the getIntValue() throws an exception if the data is empty. You can catch this exception if needed (Python try/except construct).

Other possibilities are:
 - first use getValue() and check that value is not empty before calling getIntValue()
 - only call getIntValue() if you expect the value to really be an int, e.g. depending on another test data value
