### ISSUE TITLE
Errors in demos Playback and Playback-FX

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#219]
In the demo Playback, the testsuites SelectionInTreeException and SelectionInTreeWithRegexException are failing with return "No exception"
In the demo Playback-FX, in the testsuite Document the test "insert in formatted text field (format change value)" is also failing

**Comment by dergo** [comment]
Reopened issue #160 for regression in SelectionInTreeException and SelectionInTreeWithRegexException.

Fixed Playback-FX SUT (formatted text field was actually a simple non-formatted text field).
