### ISSUE TITLE
jython module update

### ISSUE THREAD

**Issue by simjan** [qspin/qtaste#37]
The current version of jython (the one used in qtaste) is based on Python 2.2.1...

a lot of new functions have been released in python 2.5...

It should be interresting to upgrade the jython module.

The testing part of this issues has to be important cause a lot of side effects are possible!!

**Comment by dergo** [comment]
Note that jython 2.7.0 is now available.

**Comment by remybaranx** [comment]
the branch integration_jython was created to integrate jython 2.7.0 in QTaste. 
I have started this task but David will continue later.

**Comment by dergo** [comment]
Jython module is now updated to v2.7.0.
