### ISSUE TITLE
Calculator demo is not working well on some Windows platform

### ISSUE THREAD

**Issue by qspin** [qspin/qtaste#5]
Apparently, "Calculator" demo is not working on 64 Windows platform.
It could be a limitation of the version of pyWinAuto used.

In the meantime, the screencast (video) of this demo can be seen using
https://sourceforge.net/projects/qtaste/files/

(screencast_qtaste.zip)

**Comment by dergo** [comment]
Actually pyWinAuto works on 64-bit Windows with 32-bit Python, but not with 64-bit Python.
