### ISSUE TITLE
QTaste doesn't generate all Test API documentation anymore

### ISSUE THREAD

**Issue by dergo** [qspin/qtaste#72]
In QTaste 2.1.0 and current 2.2.0-SNAPSHOT, the Test API documentation generated in /target/TestAPI-doc/ doesn't include the documentation of the other Test API on which the Test API depends anymore.

E.g. at BMS level, I had the documentation of BMS, BDS, BSS, ICOMP, QTaste-Toolbox, etc..., now I only have BMS documentation.

There is a maven inheritance configuration issue in qtaste-testapi-parent:
the configuration of maven-dependency-plugin is not inherited anymore!

Also even if I override the configuration myself, JavaGUI is not included because the package name doesn't match the includes:
&lt;includes&gt;**/qtaste/testapi/api/*.java&lt;/includes&gt;
must be changed to:
&lt;includes&gt;**/qtaste/**/testapi/api/*.java&lt;/includes&gt;

**Comment by lvboque** [comment]
Could you check if it was fixed in 2.3.0 and simply regenerate the release notes?
Thks

**Comment by dergo** [comment]
Fixed in 2.3.0.
