### ISSUE TITLE
Hook for custom tasks to be performed before SUT restart

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#89]
According to the configuration, when a doStep exits in error, the SUT may be restarted by the kernel. Before the restart, for investigation purpose, it should be possible to collect some data, make screenshots, dump DB... 

Would it be possible to integrate such hook in QTaste ? Thanks !

**Comment by dergo** [comment]
You can also do some custom tasks when the test fail, by using try/except around the doStep's.

Is it ok to close this issue ?
